#!/bin/bash

set -ex

if [[ "--help" == "${1}" ]]; then
echo "bash ./sgit user.email commit"
fi

if [[ -z "${2}" ]]; then
echo "Bitte email und commit angeben!!!"
exit 1
fi

git config --global user.email "${1}"
git add --all
git commit --all -m "${2}"
git push
git show
git status
