#!/bin/bash

set -ex

if [[ "--help" == "${1}" ]]; then
echo "bash ./sgit user.email commit"
fi

if [[ -z "${2}" ]]; then
echo "Bitte email und commit angeben!!!"
exit 1
fi

git config --global user.email "${1}"
git config --global user.name "${1}"
git status
git pull
git add --all
git commit --all -m "${2}"
git show
git push
git status
